/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.project.cms.view.order;

import biz.project.cms.controller.AccountsController;
import biz.project.cms.controller.CustomerChequeController;
import biz.project.cms.controller.CustomerPaymentController;
import biz.project.cms.fileaccess.LoggerFileAcceess;
import biz.project.cms.model.Accounts;
import biz.project.cms.model.Customer;
import biz.project.cms.model.CustomerCheque;
import biz.project.cms.model.CustomerPayment;
import biz.project.cms.other.IdGenerator;
import biz.project.cms.other.Validation;
import biz.project.cms.view.main.HomeFrame;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Vihanga
 */
public class AddOrderPay extends javax.swing.JDialog {

    private String oid;
    private boolean isPrint;
    private double cash;
    private Customer customer;
    private double subTotal;
    private String netTotal;
    private String discount;
    private DefaultTableModel dtm;
    private double payTot;
    private double balance;
    private String type;
    private boolean c;

    /**
     * Creates new form AddOrderPay
     */
    public AddOrderPay(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //
        UIManager UI = new UIManager();
        UI.put("OptionPane.background", Color.white);
        UI.put("Panel.background", Color.white);
        this.setIconImage(new ImageIcon(getClass().getResource("/image/Home/Logo Company.png")).getImage());
        //
        isPrint = false;
        type = "No Payments";
        balance = 0.0;
        payTot = 0.0;
        c = true;
        cash = 0.0;
        setLocationRelativeTo(parent);
        setTitle("Add Payment");
        txtCash.requestFocus();
        lblTemp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblOrderID = new javax.swing.JLabel();
        lblOrderID1 = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();
        lblOrderID2 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        lblOrderID3 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        chkChq = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        lblOrderID4 = new javax.swing.JLabel();
        txtTot1 = new javax.swing.JTextField();
        txtChqNo = new javax.swing.JTextField();
        lblOrderID5 = new javax.swing.JLabel();
        lblOrderID6 = new javax.swing.JLabel();
        picDate = new org.jdesktop.swingx.JXDatePicker();
        lblOrderID7 = new javax.swing.JLabel();
        btnChqPay = new javax.swing.JButton();
        lblIfPay = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txtAmount = new javax.swing.JTextField();
        lblOrderID8 = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        panelTab.setBackground(new java.awt.Color(255, 255, 255));
        panelTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        panelTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(289, 239));

        lblOrderID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID.setText("Order ID");

        lblOrderID1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID1.setText("Total");

        txtTot.setEditable(false);
        txtTot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTot.setCaretColor(new java.awt.Color(116, 7, 7));

        lblOrderID2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID2.setText("Cash");

        txtCash.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCash.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCash.setCaretColor(new java.awt.Color(116, 7, 7));
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCashKeyTyped(evt);
            }
        });

        lblOrderID3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID3.setText("Balance");

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBalance.setCaretColor(new java.awt.Color(116, 7, 7));

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setText("Save & Print Invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkChq.setBackground(new java.awt.Color(255, 255, 255));
        chkChq.setForeground(new java.awt.Color(51, 51, 51));
        chkChq.setText("Also add a cheque  [F6]");
        chkChq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblOrderID2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblOrderID1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOrderID3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkChq, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(chkChq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        panelTab.addTab("<html>C<br>A<br>S<br>H<br><font color=black><b>[F7]</b></font</html>", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblOrderID4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID4.setText("Total");

        txtTot1.setEditable(false);
        txtTot1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTot1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTot1.setCaretColor(new java.awt.Color(116, 7, 7));

        txtChqNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtChqNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtChqNo.setCaretColor(new java.awt.Color(116, 7, 7));
        txtChqNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChqNoActionPerformed(evt);
            }
        });
        txtChqNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChqNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChqNoKeyTyped(evt);
            }
        });

        lblOrderID5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID5.setText("Chq. No.");

        lblOrderID6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID6.setText("Date");

        picDate.setBackground(new java.awt.Color(51, 51, 0));

        lblOrderID7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID7.setText("Bank");

        btnChqPay.setBackground(new java.awt.Color(255, 255, 0));
        btnChqPay.setText("Save & Print Invoice");
        btnChqPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChqPayActionPerformed(evt);
            }
        });

        lblIfPay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIfPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sampath Bank", "Commercial Bank", "Nation's Trust Bank", "BOC", "People's Bank", "DFCC Bank", "Pan Asia Bank", "Seylan Bank", "Other" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        txtAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAmount.setCaretColor(new java.awt.Color(116, 7, 7));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        lblOrderID8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID8.setText("Amount");

        lblTemp.setForeground(new java.awt.Color(153, 153, 153));
        lblTemp.setText("Print");
        lblTemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTempMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTempMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTempMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderID7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOrderID4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtChqNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTot1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(picDate, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIfPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnChqPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIfPay, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTemp))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtTot1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChqNo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(picDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID7, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChqPay)
                .addContainerGap())
        );

        panelTab.addTab("<html>C<br>H<br>E<br>Q<br>U<br>E<br><b>[F8]</b></html>", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelTab, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 0));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem2.setText("jMenuItem1");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem3.setText("jMenuItem1");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem4.setText("jMenuItem1");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_txtCashActionPerformed

    private void txtCashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyTyped
        Validation.priceText(txtCash);
        if (!txtCash.getText().isEmpty()) {
            calcBalance();
        } else {
            txtBalance.setText("");
        }
    }//GEN-LAST:event_txtCashKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            click();
        } catch (NumberFormatException | HeadlessException | SQLException | ClassNotFoundException ex) {
            StringWriter sw = new StringWriter();
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace(new PrintWriter(sw));
            String trace = sw.toString();
            LoggerFileAcceess.exceptionLogger(trace);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void click() throws NumberFormatException, HeadlessException, SQLException, ClassNotFoundException {
        if (!txtCash.getText().isEmpty()) {
            CustomerPayment customerPayment;
            if (Double.parseDouble(txtCash.getText()) - Double.parseDouble(txtTot.getText()) >= 0) {
                customerPayment = new CustomerPayment(newPaymentID(), getDate(), Double.parseDouble(txtTot.getText()), oid);
            } else {
                customerPayment = new CustomerPayment(newPaymentID(), getDate(), Double.parseDouble(txtCash.getText()), oid);
            }
            try {
                int addPayment = CustomerPaymentController.addPayment(customerPayment);
                if (addPayment > 0) {
                    System.out.println(AccountsController.addAccount(new Accounts(0, HomeFrame.user.getUid(), getDate(), getTime(), 2, "Add(Customer Order)", customerPayment.getAmount())));
                    JOptionPane.showMessageDialog(this, "Payment Added");
                    payTot += Double.valueOf(txtCash.getText());
                    if (!type.equals("No Payments")) {
                        type += ", Cash";
                    } else {
                        type = "Cash";
                    }
                    calcBalancePrint();
                    if (!chkChq.isSelected()) {
                        dispose();
                        printInvoice();
                    } else {
                        cash = Double.valueOf(txtCash.getText());
                        lblIfPay.setText("Cash Pay - " + cash);
                        lblOrderID4.setText("Balance");
                        txtTot1.setText(txtBalance.getText());
                        lblTemp.setVisible(true);
                        panelTab.setSelectedIndex(1);
                        txtChqNo.requestFocus();
                    }
                } else {
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "payment fail");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                StringWriter sw = new StringWriter();
                JOptionPane.showMessageDialog(this, ex.getMessage());
                ex.printStackTrace(new PrintWriter(sw));
                String trace = sw.toString();
                LoggerFileAcceess.exceptionLogger(trace);
            }
        } else {
            txtCash.requestFocus();
            int confirm = JOptionPane.showConfirmDialog(this, "Do you want to print bill without adding a payment?");
            if (confirm == 0) {
                if (!chkChq.isSelected()) {
                    dispose();
                    printInvoice();
                } else {
                    panelTab.setSelectedIndex(1);
                }
            }
        }
    }

    private void txtCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyReleased
        Validation.priceText(txtCash);
        if (!txtCash.getText().isEmpty()) {
            calcBalance();
        } else {
            txtBalance.setText("");
        }
    }//GEN-LAST:event_txtCashKeyReleased

    private void btnChqPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChqPayActionPerformed
        if (txtChqNo.getText().isEmpty()) {
            getToolkit().beep();
            txtChqNo.requestFocus();
        } else if (!validateChqDay()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "System can only accept chaques dated to today or future !");
        } else if (txtAmount.getText().isEmpty()) {
            getToolkit().beep();
            txtAmount.requestFocus();
        } else {
            try {
                CustomerPayment payment = new CustomerPayment(newPaymentID(), getDate(), Double.parseDouble(txtAmount.getText()), oid);
                int addPayment = CustomerPaymentController.addPayment(payment);
                if (addPayment > 0) {
                    System.out.println(AccountsController.addAccountChq(new Accounts(0, HomeFrame.user.getUid(), getChqDate(), getTime(), 2, "Add(Customer Order)", payment.getAmount())));
                    biz.project.cms.model.CustomerCheque cc = new CustomerCheque(txtChqNo.getText(), getChqDate(), jComboBox1.getSelectedItem().toString(), payment.getId());
                    int added = CustomerChequeController.addCustomerCheque(cc);
                    payTot += Double.valueOf(txtAmount.getText());
                    if (!type.equals("No Payments")) {
                        type += ", Cheque ";
                    } else {
                        type = "Cheque ";
                    }
                    calcBalancePrint();
                    if (added > 0) {
                        JOptionPane.showMessageDialog(this, "Cheque successfully added !");
                        dispose();
                        printInvoice();
                    } else {
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(this, "Cheque add fail!");
                    }
                } else {
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Payment add fail!");
                }

            } catch (SQLException | ClassNotFoundException | NumberFormatException | HeadlessException ex) {
                StringWriter sw = new StringWriter();
                JOptionPane.showMessageDialog(this, ex.getMessage());
                ex.printStackTrace(new PrintWriter(sw));
                String trace = sw.toString();
                LoggerFileAcceess.exceptionLogger(trace);
            }
        }
    }//GEN-LAST:event_btnChqPayActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();

    }//GEN-LAST:event_formWindowClosed

    private void txtChqNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChqNoActionPerformed
        if (!txtChqNo.getText().isEmpty()) {
            picDate.requestFocus();
        }
    }//GEN-LAST:event_txtChqNoActionPerformed

    private void chkChqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkChqActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        if (!txtAmount.getText().isEmpty()) {
            jComboBox1.showPopup();
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_txtAmountActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnChqPay.doClick();
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void lblTempMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTempMouseReleased
        printInvoice();
    }//GEN-LAST:event_lblTempMouseReleased

    private void lblTempMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTempMouseEntered
        lblTemp.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblTempMouseEntered

    private void lblTempMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTempMouseExited
        lblTemp.setForeground(Color.gray);
    }//GEN-LAST:event_lblTempMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        if (!isPrint) {
            printInvoice();
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtChqNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChqNoKeyTyped
        char c1 = evt.getKeyChar();
        if (!Character.isDigit(c1) && !(c1 == KeyEvent.VK_BACK_SPACE || c1 == KeyEvent.VK_DELETE || c1 == KeyEvent.VK_ENTER)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtChqNoKeyTyped

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        Validation.priceText(txtAmount);
    }//GEN-LAST:event_txtAmountKeyTyped

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        Validation.priceText(txtAmount);
    }//GEN-LAST:event_txtAmountKeyReleased

    private void txtChqNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChqNoKeyReleased
        Validation.limitesIntegers(txtChqNo, 18);         // TODO add your handling code here:
    }//GEN-LAST:event_txtChqNoKeyReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        if (!isPrint) {
            printInvoice();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        panelTab.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        panelTab.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (chkChq.isSelected()) {
            chkChq.setSelected(false);
        } else {
            chkChq.setSelected(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrderPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrderPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrderPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrderPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddOrderPay dialog = new AddOrderPay(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChqPay;
    private javax.swing.JCheckBox chkChq;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblIfPay;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderID1;
    private javax.swing.JLabel lblOrderID2;
    private javax.swing.JLabel lblOrderID3;
    private javax.swing.JLabel lblOrderID4;
    private javax.swing.JLabel lblOrderID5;
    private javax.swing.JLabel lblOrderID6;
    private javax.swing.JLabel lblOrderID7;
    private javax.swing.JLabel lblOrderID8;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JTabbedPane panelTab;
    private org.jdesktop.swingx.JXDatePicker picDate;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChqNo;
    private javax.swing.JTextField txtTot;
    private javax.swing.JTextField txtTot1;
    // End of variables declaration//GEN-END:variables

    private void calcBalance() {
        double balance1 = Double.parseDouble(txtCash.getText()) - Double.parseDouble(txtTot.getText());
        txtBalance.setText(balance1 + "");
    }

    public void setCID(String id) {
        this.oid = id;
        lblOrderID.setText("Order ID - " + id);
    }

    public void setAmount(double amount) {
        txtTot.setText(amount + "");
        txtTot1.setText(amount + "");
    }

    private String getDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat.format(date);
    }

    private void printInvoice() {

        if (!isPrint) {
            HashMap<String, Object> map = new HashMap<>();
            JRTableModelDataSource dataSource = new JRTableModelDataSource(dtm);
            try {
                JasperReport compileReport = JasperCompileManager.compileReport(getClass()
                        .getResourceAsStream("/reports/Invoice.jrxml"));

                map.put("INVOICE NO", oid);
                map.put("NAME", customer.getName());
                map.put("TELEPHONE", customer.getContact() + "");
                map.put("NET TOTAL", subTotal);
                map.put("DISCOUNT", "-" + discount);
                map.put("GRAND TOTAL", netTotal);
                map.put("TYPE", type);
                map.put("AMOUNT", payTot);
                map.put("BALANCE", balance);
                map.put("USER", HomeFrame.user.getUsername());
                isPrint = true;
                JasperPrint fillReport = JasperFillManager.fillReport(compileReport, map, dataSource);
                //JasperViewer.viewReport(fillReport, false);
                JasperPrintManager.printReport(fillReport, false);
            } catch (JRException ex) {
                ex.printStackTrace();
                StringWriter sw = new StringWriter();
                JOptionPane.showMessageDialog(this, ex.getMessage());
                ex.printStackTrace(new PrintWriter(sw));
                String trace = sw.toString();
                LoggerFileAcceess.exceptionLogger(trace);
            }
        }
        isPrint = true;
    }

    /**
     * @param customer the customer to set
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /**
     * @param subTotal the subTotal to set
     */
    public void setSubTotal(double subTotal) {
        this.subTotal = subTotal;
    }

    /**
     * @param netTotal the netTotal to set
     */
    public void setNetTotal(String netTotal) {
        this.netTotal = netTotal;
    }

    /**
     * @param discount the discount to set
     */
    public void setDiscount(String discount) {
        this.discount = discount;
    }

    private boolean validateChqDay() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");

        Date date1 = picDate.getDate();
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyyMMdd");

        return Integer.parseInt(dateFormat.format(date)) <= Integer.parseInt(dateFormat1.format(date1));
    }

    private String getChqDate() {
        Date date1 = picDate.getDate();
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat1.format(date1);
    }

    private String getTime() {
        Date date1 = new Date();
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("HH:mm");
        return dateFormat1.format(date1);
    }

    /**
     * @param dtm the dtm to set
     */
    public void setDtm(DefaultTableModel dtm) {
        this.dtm = dtm;
    }

    private void calcBalancePrint() {
        balance = payTot - subTotal;
    }

    private String newPaymentID() throws SQLException, ClassNotFoundException {
        return IdGenerator.getNewId(4);
    }
}
