/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.project.cms.view.supplier;

import biz.project.cms.controller.SupplierController;
import biz.project.cms.fileaccess.LoggerFileAcceess;
import biz.project.cms.model.Supplier;
import biz.project.cms.other.Validation;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vihanga
 */
public class ManageSup extends javax.swing.JDialog {

    private ArrayList<Supplier> allSuppliers = null;
    private ArrayList<Supplier> allSupplier = null;
    private Supplier supplier = null;

    /**
     * Creates new form ManageSup
     */
    public ManageSup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        UIManager UI = new UIManager();
        UI.put("OptionPane.background", Color.white);
        UI.put("Panel.background", Color.white);
        Color white = new Color(255, 255, 255);
        tblSupplier.setOpaque(true);
        tblSupplier.setFillsViewportHeight(true);
        tblSupplier.setBackground(white);
        //
        loadSupplier();
        this.setIconImage(new ImageIcon(getClass().getResource("/image/Home/Logo Company.png")).getImage());
        //    makeSearchable();
        setLocationRelativeTo(parent);
        setTitle("Manage Supplier");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        panel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        txtMobileNo = new javax.swing.JTextField();
        lblOfficeNo = new javax.swing.JLabel();
        lblSupplierName = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        lblMobileNo = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        txtOfficeNo = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(858, 481));

        tblSupplier.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Company", "Mobile", "Office", "Fax", "Email", "Due Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSupplier.setRowHeight(22);
        tblSupplier.setSelectionBackground(new java.awt.Color(0, 153, 102));
        tblSupplier.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblSupplier.getTableHeader().setReorderingAllowed(false);
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supplier Info :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(102, 102, 255))); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtMobileNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMobileNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNoActionPerformed(evt);
            }
        });
        txtMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyTyped(evt);
            }
        });

        lblOfficeNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOfficeNo.setText("Office No   :");

        lblSupplierName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSupplierName.setText("Supplier Name   :");

        txtSupplierName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtSupplierName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });
        txtSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSupplierNameKeyTyped(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmail.setText("Email   :");

        lblCompanyName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCompanyName.setText("Company Name   :");

        lblFax.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFax.setText("Fax   :");

        lblMobileNo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMobileNo.setText("Mobile No   :");

        txtFax.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtFax.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtFax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxActionPerformed(evt);
            }
        });
        txtFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFaxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFaxKeyTyped(evt);
            }
        });

        txtOfficeNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtOfficeNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtOfficeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOfficeNoActionPerformed(evt);
            }
        });
        txtOfficeNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOfficeNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOfficeNoKeyTyped(evt);
            }
        });

        txtCompanyName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCompanyName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });
        txtCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCompanyNameKeyReleased(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSupplierName)
                            .addComponent(lblCompanyName)
                            .addComponent(lblMobileNo)
                            .addComponent(lblOfficeNo)
                            .addComponent(lblFax)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(txtMobileNo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtOfficeNo)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFax)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobileNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOfficeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOfficeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) tblSupplier.getModel();
            Supplier supplier1 = SupplierController.searchSupplier(dtm.getValueAt(tblSupplier.getSelectedRow(), 1).toString());
            if (supplier1 != null) {
                supplier = supplier1;
                txtSupplierName.setText(supplier1.getName());
                txtCompanyName.setText(supplier1.getCompany());
                txtMobileNo.setText(supplier1.getMobile() + "");
                txtOfficeNo.setText(supplier1.getOffice() + "");
                txtFax.setText(supplier1.getFax() + "");
                txtEmail.setText(supplier1.getEmail());
            } else {
                txtSupplierName.setText("");
                txtCompanyName.setText("");
                txtMobileNo.setText("");
                txtOfficeNo.setText("");
                txtFax.setText("");
                txtEmail.setText("");
                loadSupplier();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            StringWriter sw = new StringWriter();
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace(new PrintWriter(sw));
            String trace = sw.toString();
            LoggerFileAcceess.exceptionLogger(trace);
        }
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateSupplier();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNoActionPerformed
        txtOfficeNo.requestFocus();
    }//GEN-LAST:event_txtMobileNoActionPerformed

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        txtCompanyName.requestFocus();
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void txtFaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxActionPerformed
        txtEmail.requestFocus();
    }//GEN-LAST:event_txtFaxActionPerformed

    private void txtOfficeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOfficeNoActionPerformed
        txtFax.requestFocus();
    }//GEN-LAST:event_txtOfficeNoActionPerformed

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        txtMobileNo.requestFocus();
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierNameKeyReleased
        Validation.name(txtSupplierName);          // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameKeyReleased

    private void txtSupplierNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierNameKeyTyped
        Validation.name(txtSupplierName);          // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameKeyTyped

    private void txtCompanyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompanyNameKeyReleased
    }//GEN-LAST:event_txtCompanyNameKeyReleased

    private void txtMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyTyped
        Validation.phoneNumber(txtMobileNo, evt);         // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoKeyTyped

    private void txtMobileNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyReleased
        Validation.phoneNumber(txtMobileNo, evt);         // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoKeyReleased

    private void txtOfficeNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOfficeNoKeyReleased
        Validation.phoneNumber(txtOfficeNo, evt);              // TODO add your handling code here:
    }//GEN-LAST:event_txtOfficeNoKeyReleased

    private void txtOfficeNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOfficeNoKeyTyped
        Validation.phoneNumber(txtOfficeNo, evt);              // TODO add your handling code here:
    }//GEN-LAST:event_txtOfficeNoKeyTyped

    private void txtFaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyReleased
        Validation.phoneNumber(txtFax, evt);          // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxKeyReleased

    private void txtFaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxKeyTyped
        Validation.phoneNumber(txtFax, evt);          // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageSup dialog = new ManageSup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblMobileNo;
    private javax.swing.JLabel lblOfficeNo;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtOfficeNo;
    private javax.swing.JTextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
private void loadSupplier() {
        DefaultTableModel dtm = (DefaultTableModel) tblSupplier.getModel();
        dtm.setRowCount(0);
        // comboSearch.removeAllItems();
        //comboSearch.addItem("All Customers");
        try {
            allSuppliers = SupplierController.allSuppliersWithDuePayment();
            allSupplier = SupplierController.allSuppliers();
//            if (checkBoxPayments.isSelected()) {
//                for (Supplier supplier1 : allSuppliers) {
//                    if (supplier1.getDuePayment() != 0) {
//                        Object[] rowData = {supplier1.getName(), supplier1.getCompany(), supplier1.getMobile(), supplier1.getOffice(), supplier1.getFax(), supplier1.getEmail(), supplier1.getDuePayment()};
//                        dtm.addRow(rowData);
//                        comboSearch.addItem(supplier1.getCompany() + " - " + supplier1.getName());
//                    }
//
//                }
//            } else {
            for (Supplier supplier1 : allSuppliers) {
                Object[] rowData = {supplier1.getName(), supplier1.getCompany(), supplier1.getMobile(), supplier1.getOffice(), supplier1.getFax(), supplier1.getEmail(), supplier1.getDuePayment()};
                dtm.addRow(rowData);
                //  comboSearch.addItem(supplier1.getCompany() + " - " + supplier1.getName());
            }
            for (Supplier supplier1 : allSupplier) {
                boolean b = true;
                for (Supplier s : allSuppliers) {
                    if (s.getSupId() == supplier1.getSupId()) {
                        b = false;
                        break;
                    }
                }
                if (b == true) {
                    Object[] rowData = {supplier1.getName(), supplier1.getCompany(), supplier1.getMobile(), supplier1.getOffice(), supplier1.getFax(), supplier1.getEmail(), "0.00"};
                    dtm.addRow(rowData);
                    //     comboSearch.addItem(supplier1.getCompany() + " - " + supplier1.getName());
                }
            }

//            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageSup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//    private void makeSearchable() {
//        SearchCombo searchCombo = new SearchCombo();
//        searchCombo.setSearchableCombo(comboSearch, true, "No Supplier Found !", false);
//    }
//    private void setValuesToText() {
//        comboSearch.setSelectedIndex(tblSupplier.getSelectedRow());
//    }
    private void updateSupplier() {
        try {
            if (supplier != null && txtCompanyName.getText().equals("") != true) {
                supplier.setCompany(txtCompanyName.getText());
                supplier.setName(txtSupplierName.getText());
                supplier.setMobile(Integer.parseInt(txtMobileNo.getText()));
                supplier.setOffice(Integer.parseInt(txtOfficeNo.getText()));
                supplier.setFax(Integer.parseInt(txtFax.getText()));
                supplier.setEmail(txtEmail.getText());
                try {
                    boolean updateSupplier = SupplierController.updateSupplier(supplier);
                    if (updateSupplier) {
                        JOptionPane.showMessageDialog(this, "Supplier Updated Successfully");
                        loadSupplier();
                    } else {
                        JOptionPane.showMessageDialog(this, "Can,t Update the Supplier");
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    StringWriter sw = new StringWriter();
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    ex.printStackTrace(new PrintWriter(sw));
                    String trace = sw.toString();
                    LoggerFileAcceess.exceptionLogger(trace);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Can,t Update the Supplier");
            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Invalid contact number !");
        }
    }

    private void deleteSupplier() {
        try {
            int deleteSupplier = SupplierController.deleteSupplier(supplier.getSupId());
            if (deleteSupplier > 0) {
                JOptionPane.showMessageDialog(this, "Supplier Deleted Successfully");
                txtSupplierName.setText("");
                txtCompanyName.setText("");
                txtMobileNo.setText("");
                txtOfficeNo.setText("");
                txtFax.setText("");
                txtEmail.setText("");
                loadSupplier();
            } else {
                JOptionPane.showMessageDialog(this, "Can't Delete this Supplier ");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageSup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//    private void searchCombo() {
//        if (comboSearch.getSelectedIndex() != -1) {
//            try {
//                String[] split = comboSearch.getSelectedItem().toString().split(" - ");
//                Supplier supplier1 = SupplierController.searchSupplier(split[0]);
//                if (supplier1 != null) {
//                    supplier = supplier1;
//                    txtSupplierName.setText(supplier1.getName());
//                    txtCompanyName.setText(supplier1.getCompany());
//                    txtMobileNo.setText(supplier1.getMobile() + "");
//                    txtOfficeNo.setText(supplier1.getOffice() + "");
//                    txtFax.setText(supplier1.getFax() + "");
//                    txtEmail.setText(supplier1.getEmail());
//                }
//            } catch (ClassNotFoundException | SQLException ex) {
//                Logger.getLogger(ManageSupplier.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//    }
}
