/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.project.cms.view.other;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vihanga
 */
public class Shorcuts extends javax.swing.JDialog {

    private JTable tableShort;

    private JScrollPane scrollTable = new JScrollPane(tableShort);
    private int xMouse;
    private int yMouse;

    /**
     * Creates new form
     */
    public Shorcuts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //
        UIManager UI = new UIManager();
        UI.put("OptionPane.background", Color.white);
        UI.put("Panel.background", Color.white);
        //
        this.setIconImage(new ImageIcon(getClass().getResource("/image/Home/Logo Company.png")).getImage());
        setLocationRelativeTo(null);
        setTitle("POS - Shortcuts");
        try {
            addTable();
        } catch (NotBoundException ex) {
            Logger.getLogger(Shorcuts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Shorcuts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Shorcuts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addTable() throws NotBoundException, ClassNotFoundException,
            IOException {

        String[] columnNames = {"", ""};
        Object[][] rows = new Object[10][2];

        rows[0][0] = "Sell Price";
        rows[1][0] = "Insert Quantity";
        rows[2][0] = "Insert Code";
        rows[3][0] = "Barcode";
        rows[4][0] = "Select Desc";
        rows[5][0] = "Insert Customer";
        rows[6][0] = "Add to Table";
        rows[7][0] = "Save ";
        rows[8][0] = "Calculator";
        rows[9][0] = "Clear All";

        rows[0][1] = "F11";
        rows[1][1] = "F12";
        rows[2][1] = "F7";
        rows[3][1] = "F8";
        rows[4][1] = "F9";
        rows[5][1] = "Alt+C";
        rows[6][1] = "Insert";
        rows[7][1] = "F3";
        rows[8][1] = "Ctrl+SPACE";
        rows[9][1] = "Alt+X";

        DefaultTableModel dtm = new DefaultTableModel(rows, columnNames) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tableShort = new JTable() {
//            @Override
//            public Class getColumnClass(int column) {
//                return getValueAt(0, 1).getClass();
//            }
        };
        tableShort.setFont(new Font("Arial", 0, 15));
        tableShort.setModel(dtm);
        tableShort.setPreferredScrollableViewportSize(tableShort
                .getPreferredSize());
        tableShort.setRowHeight(28);
        tableShort.setSelectionBackground(new Color(255, 240, 140));
        tableShort.setSelectionForeground(new Color(100, 30, 30));
        tableShort.setTableHeader(null);
        tableShort.getColumnModel().getColumn(1).setPreferredWidth(10);
        tableShort.getColumnModel().getColumn(1).setResizable(false);
        scrollTable = new JScrollPane(tableShort);
        jPanel1.add(scrollTable,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 355, 287));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Frame = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Frame.setBackground(new java.awt.Color(51, 51, 51));
        Frame.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        Frame.setForeground(new java.awt.Color(255, 255, 255));
        Frame.setText("    Shortcuts");
        Frame.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Frame.setOpaque(true);
        Frame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FrameMouseMoved(evt);
            }
        });
        Frame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameMousePressed(evt);
            }
        });
        jPanel2.add(Frame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 356, 42));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 356, 280));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 320));

        closeLabel.setBackground(new java.awt.Color(51, 51, 51));
        closeLabel.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        closeLabel.setText("Click to Close     ");
        closeLabel.setOpaque(true);
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeLabelMouseExited(evt);
            }
        });
        getContentPane().add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 356, 30));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 0));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameMouseDragged

    private void FrameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_FrameMouseMoved

    private void FrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameMousePressed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void closeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseEntered
        closeLabel.setForeground(Color.ORANGE);
    }//GEN-LAST:event_closeLabelMouseEntered

    private void closeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseExited
        closeLabel.setForeground(Color.white);
    }//GEN-LAST:event_closeLabelMouseExited

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shorcuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shorcuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shorcuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shorcuts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Shorcuts dialog = new Shorcuts(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frame;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
