/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.project.cms.view.accounts;

import biz.project.cms.controller.AccountsController;
import biz.project.cms.fileaccess.LoggerFileAcceess;
import biz.project.cms.model.Accounts;
import biz.project.cms.model.User;
import biz.project.cms.other.Validation;
import biz.project.cms.view.main.HomeFrame;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Kisal Suranjaya
 */
public class ManageAccounts extends javax.swing.JDialog {

    private StringWriter sw;
    /**
     * Creates new form ManageAccounts
     */
    private String selectedBtn;
    private Accounts accounts;
    private Date sqlDate;
    private String utilTime;
    private int type;
    private double amount;
    private int addAccount;
    private User userID;

    public ManageAccounts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sw = new StringWriter();
        //
        UIManager UI = new UIManager();
        UI.put("OptionPane.background", Color.white);
        UI.put("Panel.background", Color.white);
        //
        txtPettyCashAddDesc.requestFocus();
        setLocationRelativeTo(parent);
        userID = HomeFrame.user;
        this.setIconImage(new ImageIcon(getClass().getResource("/image/Home/Logo Company.png")).getImage());
        curruntDate();
        curruntTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelPettyCash = new javax.swing.JPanel();
        panelWarrentyInfo = new javax.swing.JPanel();
        txtPettyCashAddAmount = new javax.swing.JTextField();
        lblPeriod = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        txtPettyCashAddDesc = new javax.swing.JTextField();
        btnSavePettyCash = new javax.swing.JButton();
        panelWarrentyInfo2 = new javax.swing.JPanel();
        txtPettyCashWithdrawAmount = new javax.swing.JTextField();
        lblPeriod2 = new javax.swing.JLabel();
        lblSerial2 = new javax.swing.JLabel();
        txtPettyCashWithdrawDesc = new javax.swing.JTextField();
        btnWithdrawPettyCash = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panelWarrentyInfo1 = new javax.swing.JPanel();
        txtDrawerCashAddAmount = new javax.swing.JTextField();
        lblPeriod1 = new javax.swing.JLabel();
        lblSerial1 = new javax.swing.JLabel();
        txtDrawerCashAddDesc = new javax.swing.JTextField();
        btnSaveDrawerCash = new javax.swing.JButton();
        panelWarrentyInfo3 = new javax.swing.JPanel();
        txtDrawerCashWithdrawAmount = new javax.swing.JTextField();
        lblPeriod3 = new javax.swing.JLabel();
        lblSerial3 = new javax.swing.JLabel();
        txtDrawerCashWithdrawDesc = new javax.swing.JTextField();
        btnWithdrawDrawerCash = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        hlViewAccounts = new org.jdesktop.swingx.JXHyperlink();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accounts");
        setResizable(false);

        panelmain.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons/Accounts.png"))); // NOI18N
        jLabel1.setText("Manage Accounts");
        jLabel1.setIconTextGap(8);

        panelPettyCash.setBackground(new java.awt.Color(255, 255, 255));
        panelPettyCash.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Petty Cash", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        panelWarrentyInfo.setBackground(new java.awt.Color(255, 255, 255));
        panelWarrentyInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Cash", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        txtPettyCashAddAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPettyCashAddAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPettyCashAddAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPettyCashAddAmountActionPerformed(evt);
            }
        });
        txtPettyCashAddAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPettyCashAddAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPettyCashAddAmountKeyTyped(evt);
            }
        });

        lblPeriod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPeriod.setText("Description :");

        lblSerial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSerial.setText("Amount :");

        txtPettyCashAddDesc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPettyCashAddDesc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPettyCashAddDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPettyCashAddDescActionPerformed(evt);
            }
        });
        txtPettyCashAddDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPettyCashAddDescKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPettyCashAddDescKeyReleased(evt);
            }
        });

        btnSavePettyCash.setBackground(new java.awt.Color(255, 255, 255));
        btnSavePettyCash.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSavePettyCash.setText("SAVE");
        btnSavePettyCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSavePettyCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePettyCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWarrentyInfoLayout = new javax.swing.GroupLayout(panelWarrentyInfo);
        panelWarrentyInfo.setLayout(panelWarrentyInfoLayout);
        panelWarrentyInfoLayout.setHorizontalGroup(
            panelWarrentyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPeriod)
                    .addComponent(lblSerial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelWarrentyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPettyCashAddDesc)
                    .addComponent(txtPettyCashAddAmount))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWarrentyInfoLayout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(btnSavePettyCash, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelWarrentyInfoLayout.setVerticalGroup(
            panelWarrentyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriod)
                    .addComponent(txtPettyCashAddDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelWarrentyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial)
                    .addComponent(txtPettyCashAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSavePettyCash, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panelWarrentyInfo2.setBackground(new java.awt.Color(255, 255, 255));
        panelWarrentyInfo2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Withdraw", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        txtPettyCashWithdrawAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPettyCashWithdrawAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPettyCashWithdrawAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPettyCashWithdrawAmountActionPerformed(evt);
            }
        });
        txtPettyCashWithdrawAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPettyCashWithdrawAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPettyCashWithdrawAmountKeyTyped(evt);
            }
        });

        lblPeriod2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPeriod2.setText("Description :");

        lblSerial2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSerial2.setText("Amount :");

        txtPettyCashWithdrawDesc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPettyCashWithdrawDesc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtPettyCashWithdrawDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPettyCashWithdrawDescActionPerformed(evt);
            }
        });
        txtPettyCashWithdrawDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPettyCashWithdrawDescKeyReleased(evt);
            }
        });

        btnWithdrawPettyCash.setBackground(new java.awt.Color(255, 255, 255));
        btnWithdrawPettyCash.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawPettyCash.setText("Withdraw");
        btnWithdrawPettyCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWithdrawPettyCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawPettyCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWarrentyInfo2Layout = new javax.swing.GroupLayout(panelWarrentyInfo2);
        panelWarrentyInfo2.setLayout(panelWarrentyInfo2Layout);
        panelWarrentyInfo2Layout.setHorizontalGroup(
            panelWarrentyInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnWithdrawPettyCash, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelWarrentyInfo2Layout.createSequentialGroup()
                        .addGroup(panelWarrentyInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPeriod2)
                            .addComponent(lblSerial2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelWarrentyInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPettyCashWithdrawDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(txtPettyCashWithdrawAmount))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelWarrentyInfo2Layout.setVerticalGroup(
            panelWarrentyInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriod2)
                    .addComponent(txtPettyCashWithdrawDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelWarrentyInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial2)
                    .addComponent(txtPettyCashWithdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWithdrawPettyCash, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPettyCashLayout = new javax.swing.GroupLayout(panelPettyCash);
        panelPettyCash.setLayout(panelPettyCashLayout);
        panelPettyCashLayout.setHorizontalGroup(
            panelPettyCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPettyCashLayout.createSequentialGroup()
                .addGroup(panelPettyCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPettyCashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelWarrentyInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPettyCashLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelWarrentyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelPettyCashLayout.setVerticalGroup(
            panelPettyCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPettyCashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelWarrentyInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWarrentyInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drawer Cash", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 51))); // NOI18N

        panelWarrentyInfo1.setBackground(new java.awt.Color(255, 255, 255));
        panelWarrentyInfo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Cash", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        txtDrawerCashAddAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDrawerCashAddAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDrawerCashAddAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrawerCashAddAmountActionPerformed(evt);
            }
        });
        txtDrawerCashAddAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDrawerCashAddAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDrawerCashAddAmountKeyTyped(evt);
            }
        });

        lblPeriod1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPeriod1.setText("Description :");

        lblSerial1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSerial1.setText("Amount :");

        txtDrawerCashAddDesc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDrawerCashAddDesc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDrawerCashAddDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrawerCashAddDescActionPerformed(evt);
            }
        });
        txtDrawerCashAddDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDrawerCashAddDescKeyReleased(evt);
            }
        });

        btnSaveDrawerCash.setBackground(new java.awt.Color(255, 255, 255));
        btnSaveDrawerCash.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSaveDrawerCash.setText("SAVE");
        btnSaveDrawerCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveDrawerCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDrawerCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWarrentyInfo1Layout = new javax.swing.GroupLayout(panelWarrentyInfo1);
        panelWarrentyInfo1.setLayout(panelWarrentyInfo1Layout);
        panelWarrentyInfo1Layout.setHorizontalGroup(
            panelWarrentyInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveDrawerCash, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelWarrentyInfo1Layout.createSequentialGroup()
                        .addGroup(panelWarrentyInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPeriod1)
                            .addComponent(lblSerial1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelWarrentyInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDrawerCashAddDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txtDrawerCashAddAmount))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWarrentyInfo1Layout.setVerticalGroup(
            panelWarrentyInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriod1)
                    .addComponent(txtDrawerCashAddDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelWarrentyInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial1)
                    .addComponent(txtDrawerCashAddAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveDrawerCash, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panelWarrentyInfo3.setBackground(new java.awt.Color(255, 255, 255));
        panelWarrentyInfo3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Withdraw", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N

        txtDrawerCashWithdrawAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDrawerCashWithdrawAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDrawerCashWithdrawAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrawerCashWithdrawAmountActionPerformed(evt);
            }
        });
        txtDrawerCashWithdrawAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDrawerCashWithdrawAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDrawerCashWithdrawAmountKeyTyped(evt);
            }
        });

        lblPeriod3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPeriod3.setText("Description :");

        lblSerial3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSerial3.setText("Amount :");

        txtDrawerCashWithdrawDesc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDrawerCashWithdrawDesc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDrawerCashWithdrawDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDrawerCashWithdrawDescActionPerformed(evt);
            }
        });
        txtDrawerCashWithdrawDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDrawerCashWithdrawDescKeyReleased(evt);
            }
        });

        btnWithdrawDrawerCash.setBackground(new java.awt.Color(255, 255, 255));
        btnWithdrawDrawerCash.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawDrawerCash.setText("Withdraw");
        btnWithdrawDrawerCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWithdrawDrawerCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawDrawerCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWarrentyInfo3Layout = new javax.swing.GroupLayout(panelWarrentyInfo3);
        panelWarrentyInfo3.setLayout(panelWarrentyInfo3Layout);
        panelWarrentyInfo3Layout.setHorizontalGroup(
            panelWarrentyInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPeriod3)
                    .addComponent(lblSerial3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelWarrentyInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDrawerCashWithdrawAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(txtDrawerCashWithdrawDesc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelWarrentyInfo3Layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addComponent(btnWithdrawDrawerCash, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelWarrentyInfo3Layout.setVerticalGroup(
            panelWarrentyInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrentyInfo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelWarrentyInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriod3)
                    .addComponent(txtDrawerCashWithdrawDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panelWarrentyInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial3)
                    .addComponent(txtDrawerCashWithdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnWithdrawDrawerCash, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelWarrentyInfo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelWarrentyInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelWarrentyInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelWarrentyInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("To view your Account Details ");

        hlViewAccounts.setText("Click Here");
        hlViewAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlViewAccountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmainLayout = new javax.swing.GroupLayout(panelmain);
        panelmain.setLayout(panelmainLayout);
        panelmainLayout.setHorizontalGroup(
            panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmainLayout.createSequentialGroup()
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelmainLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(panelPettyCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelmainLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hlViewAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelmainLayout.setVerticalGroup(
            panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmainLayout.createSequentialGroup()
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelmainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hlViewAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPettyCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPettyCashAddAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPettyCashAddAmountActionPerformed
        btnSavePettyCash.doClick();
    }//GEN-LAST:event_txtPettyCashAddAmountActionPerformed

    private void txtPettyCashAddAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPettyCashAddAmountKeyReleased
        Validation.priceText(txtPettyCashAddAmount);
    }//GEN-LAST:event_txtPettyCashAddAmountKeyReleased

    private void txtPettyCashAddDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPettyCashAddDescActionPerformed
        txtPettyCashAddAmount.requestFocus();
    }//GEN-LAST:event_txtPettyCashAddDescActionPerformed

    private void txtPettyCashAddDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPettyCashAddDescKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPettyCashAddDescKeyReleased

    private void btnSavePettyCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePettyCashActionPerformed
        selectedBtn = "SavePettyCash";
        saveAccount();
    }//GEN-LAST:event_btnSavePettyCashActionPerformed

    private void txtDrawerCashAddAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrawerCashAddAmountActionPerformed
        btnSaveDrawerCash.doClick();
    }//GEN-LAST:event_txtDrawerCashAddAmountActionPerformed

    private void txtDrawerCashAddAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrawerCashAddAmountKeyReleased
        Validation.priceText(txtDrawerCashAddAmount);
    }//GEN-LAST:event_txtDrawerCashAddAmountKeyReleased

    private void txtDrawerCashAddDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrawerCashAddDescActionPerformed
        txtDrawerCashAddAmount.requestFocus();
    }//GEN-LAST:event_txtDrawerCashAddDescActionPerformed

    private void txtDrawerCashAddDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrawerCashAddDescKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrawerCashAddDescKeyReleased

    private void btnSaveDrawerCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDrawerCashActionPerformed
        selectedBtn = "SaveDrawerCash";
        saveAccount();
    }//GEN-LAST:event_btnSaveDrawerCashActionPerformed

    private void txtPettyCashWithdrawAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPettyCashWithdrawAmountActionPerformed
        btnWithdrawPettyCash.doClick();
    }//GEN-LAST:event_txtPettyCashWithdrawAmountActionPerformed

    private void txtPettyCashWithdrawAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPettyCashWithdrawAmountKeyReleased
        Validation.priceText(txtPettyCashWithdrawAmount);
    }//GEN-LAST:event_txtPettyCashWithdrawAmountKeyReleased

    private void txtPettyCashWithdrawDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPettyCashWithdrawDescActionPerformed
    txtPettyCashWithdrawAmount.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPettyCashWithdrawDescActionPerformed

    private void txtPettyCashWithdrawDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPettyCashWithdrawDescKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPettyCashWithdrawDescKeyReleased

    private void btnWithdrawPettyCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawPettyCashActionPerformed
        selectedBtn = "WithdrawPettyCash";
        saveAccount();
    }//GEN-LAST:event_btnWithdrawPettyCashActionPerformed

    private void txtDrawerCashWithdrawAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrawerCashWithdrawAmountActionPerformed
        btnWithdrawDrawerCash.doClick();
    }//GEN-LAST:event_txtDrawerCashWithdrawAmountActionPerformed

    private void txtDrawerCashWithdrawAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrawerCashWithdrawAmountKeyReleased
        Validation.priceText(txtDrawerCashWithdrawAmount);
    }//GEN-LAST:event_txtDrawerCashWithdrawAmountKeyReleased

    private void txtDrawerCashWithdrawDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDrawerCashWithdrawDescActionPerformed
        txtDrawerCashWithdrawAmount.requestFocus();
    }//GEN-LAST:event_txtDrawerCashWithdrawDescActionPerformed

    private void txtDrawerCashWithdrawDescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrawerCashWithdrawDescKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDrawerCashWithdrawDescKeyReleased

    private void btnWithdrawDrawerCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawDrawerCashActionPerformed
        selectedBtn = "WithdrawDrawerCash";
        saveAccount();
    }//GEN-LAST:event_btnWithdrawDrawerCashActionPerformed

    private void hlViewAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlViewAccountsActionPerformed
        if (HomeFrame.user.getType().equals("admin")) {
            new VewAccountDetails().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Sorry, You don't have administrative rights!", "WARNING", 0);
        }
    }//GEN-LAST:event_hlViewAccountsActionPerformed

    private void txtPettyCashAddAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPettyCashAddAmountKeyTyped
        Validation.priceText(txtPettyCashAddAmount);
    }//GEN-LAST:event_txtPettyCashAddAmountKeyTyped

    private void txtDrawerCashAddAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrawerCashAddAmountKeyTyped
        Validation.priceText(txtDrawerCashAddAmount);
    }//GEN-LAST:event_txtDrawerCashAddAmountKeyTyped

    private void txtPettyCashWithdrawAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPettyCashWithdrawAmountKeyTyped
        Validation.priceText(txtPettyCashWithdrawAmount);
    }//GEN-LAST:event_txtPettyCashWithdrawAmountKeyTyped

    private void txtDrawerCashWithdrawAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrawerCashWithdrawAmountKeyTyped
        Validation.priceText(txtDrawerCashWithdrawAmount);
    }//GEN-LAST:event_txtDrawerCashWithdrawAmountKeyTyped

    private void txtPettyCashAddDescKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPettyCashAddDescKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_txtPettyCashAddDescKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageAccounts dialog = new ManageAccounts(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDrawerCash;
    private javax.swing.JButton btnSavePettyCash;
    private javax.swing.JButton btnWithdrawDrawerCash;
    private javax.swing.JButton btnWithdrawPettyCash;
    private org.jdesktop.swingx.JXHyperlink hlViewAccounts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPeriod;
    private javax.swing.JLabel lblPeriod1;
    private javax.swing.JLabel lblPeriod2;
    private javax.swing.JLabel lblPeriod3;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblSerial1;
    private javax.swing.JLabel lblSerial2;
    private javax.swing.JLabel lblSerial3;
    private javax.swing.JPanel panelPettyCash;
    private javax.swing.JPanel panelWarrentyInfo;
    private javax.swing.JPanel panelWarrentyInfo1;
    private javax.swing.JPanel panelWarrentyInfo2;
    private javax.swing.JPanel panelWarrentyInfo3;
    private javax.swing.JPanel panelmain;
    private javax.swing.JTextField txtDrawerCashAddAmount;
    private javax.swing.JTextField txtDrawerCashAddDesc;
    private javax.swing.JTextField txtDrawerCashWithdrawAmount;
    private javax.swing.JTextField txtDrawerCashWithdrawDesc;
    private javax.swing.JTextField txtPettyCashAddAmount;
    private javax.swing.JTextField txtPettyCashAddDesc;
    private javax.swing.JTextField txtPettyCashWithdrawAmount;
    private javax.swing.JTextField txtPettyCashWithdrawDesc;
    // End of variables declaration//GEN-END:variables

    private void curruntDate() {
        java.util.Calendar cal = java.util.Calendar.getInstance();
        java.util.Date utilDate = cal.getTime();
        sqlDate = new Date(utilDate.getTime());
    }

    private void curruntTime() {
        java.util.Calendar cal = java.util.Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        utilTime = sdf.format(cal.getTime());
    }

    private void saveAccount() {
        switch (selectedBtn) {
            case "SavePettyCash":
                type = 0;
                amount = Double.parseDouble(txtPettyCashAddAmount.getText());

                accounts = new Accounts(0, userID.getUid(), sqlDate + "", utilTime, 1, "Add(" + txtPettyCashAddDesc.getText() + ")", amount);
                 {
                    try {
                        addAccount = AccountsController.addAccount(accounts);
                        if (addAccount > 0) {
                            JOptionPane.showMessageDialog(rootPane, "Petty Cash Added Success !.....");
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Petty Cash Added falied !.....");
                        }
                    } catch (SQLException | ClassNotFoundException ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                        ex.printStackTrace(new PrintWriter(sw));
                        String trace = sw.toString();
                        LoggerFileAcceess.exceptionLogger(trace);;
                    }
                }

                break;

            case "SaveDrawerCash":
                type = 0;
                amount = Double.parseDouble(txtDrawerCashAddAmount.getText());

                accounts = new Accounts(0, userID.getUid(), sqlDate + "", utilTime, 2, "Add(" + txtDrawerCashAddDesc.getText() + ")", amount);
                try {
                    addAccount = AccountsController.addAccount(accounts);
                    if (addAccount > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Drawer Cash Added Success !.....");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Drawer Cash Added falied !.....");
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    ex.printStackTrace(new PrintWriter(sw));
                    String trace = sw.toString();
                    LoggerFileAcceess.exceptionLogger(trace);
                }

                break;

            case "WithdrawPettyCash":
                type = 0;
                amount = Double.parseDouble(txtPettyCashWithdrawAmount.getText());

                accounts = new Accounts(0, userID.getUid(), sqlDate + "", utilTime, 1, "Withdraw(" + txtPettyCashWithdrawDesc.getText() + ")", -amount);

                try {
                    addAccount = AccountsController.addAccount(accounts);
                    if (addAccount > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Petty Cash Withdraw Success !.....");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Petty Cash Withdraw falied !.....");
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    ex.printStackTrace(new PrintWriter(sw));
                    String trace = sw.toString();
                    LoggerFileAcceess.exceptionLogger(trace);
                }

                break;

            case "WithdrawDrawerCash":
                type = 0;
                amount = Double.parseDouble(txtDrawerCashWithdrawAmount.getText());

                accounts = new Accounts(0, userID.getUid(), sqlDate + "", utilTime, 2, "Withdraw(" + txtDrawerCashWithdrawDesc.getText() + ")", -amount);

                try {
                    addAccount = AccountsController.addAccount(accounts);
                    if (addAccount > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Drawer Cash Withdraw Success !.....");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Drawer Cash Withdraw falied !.....");
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    ex.printStackTrace(new PrintWriter(sw));
                    String trace = sw.toString();
                    LoggerFileAcceess.exceptionLogger(trace);
                }

                break;
        }
    }
}
