/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.project.cms.view.grn;

import biz.project.cms.controller.AccountsController;
import biz.project.cms.controller.MyChequeController;
import biz.project.cms.controller.MyPaymentController;
import biz.project.cms.fileaccess.LoggerFileAcceess;
import biz.project.cms.model.Accounts;
import biz.project.cms.model.MyCheque;
import biz.project.cms.model.MyPayment;
import biz.project.cms.other.IdGenerator;
import biz.project.cms.other.Validation;
import biz.project.cms.view.main.HomeFrame;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Vihanga
 */
public class AddGRNPay extends javax.swing.JDialog {

    private String cid;
    private double cash;

    /**
     * Creates new form AddGRNPay
     */
    public AddGRNPay(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //
        UIManager UI = new UIManager();
        this.setIconImage(new ImageIcon(getClass().getResource("/image/Home/Logo Company.png")).getImage());
        UI.put("OptionPane.background", Color.white);
        UI.put("Panel.background", Color.white);
        //
        cash = 0.00;
        txtCash.requestFocus();
        setLocationRelativeTo(parent);
        setTitle("Add Payment");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JPanel();
        panelTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblOrderID = new javax.swing.JLabel();
        lblOrderID1 = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();
        lblOrderID2 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        lblOrderID3 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        chkChq = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        txtChqNo1 = new javax.swing.JTextField();
        lblOrderID7 = new javax.swing.JLabel();
        lblOrderID8 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        txtAmount = new javax.swing.JTextField();
        lblOrderID9 = new javax.swing.JLabel();
        btnChqPay = new javax.swing.JButton();
        lblOrderID10 = new javax.swing.JLabel();
        txtTot2 = new javax.swing.JTextField();
        lblOrderID11 = new javax.swing.JLabel();
        picDate = new org.jdesktop.swingx.JXDatePicker();
        lblIfPay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pane.setBackground(new java.awt.Color(255, 255, 255));

        panelTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        panelTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblOrderID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID.setText("GRN ID");

        lblOrderID1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID1.setText("Total");

        txtTot.setEditable(false);
        txtTot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTot.setCaretColor(new java.awt.Color(116, 7, 7));
        txtTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotActionPerformed(evt);
            }
        });

        lblOrderID2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID2.setText("Cash");

        txtCash.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCash.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtCash.setCaretColor(new java.awt.Color(116, 7, 7));
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCashKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCashKeyTyped(evt);
            }
        });

        lblOrderID3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID3.setText("Balance");

        txtBalance.setEditable(false);
        txtBalance.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtBalance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBalance.setCaretColor(new java.awt.Color(116, 7, 7));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkChq.setBackground(new java.awt.Color(255, 255, 255));
        chkChq.setForeground(new java.awt.Color(51, 51, 51));
        chkChq.setText("Also add a cheque");
        chkChq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkChqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOrderID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOrderID2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOrderID1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblOrderID3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkChq, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderID3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(chkChq)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        panelTab.addTab("<html>C<br>A<br>S<br>H</html>", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtChqNo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtChqNo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtChqNo1.setCaretColor(new java.awt.Color(116, 7, 7));
        txtChqNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChqNo1ActionPerformed(evt);
            }
        });
        txtChqNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChqNo1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChqNo1KeyTyped(evt);
            }
        });

        lblOrderID7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID7.setText("Chq. No.");

        lblOrderID8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID8.setText("Date");

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sampath Bank", "Commercial Bank", "Nation's Trust Bank", "BOC", "People's Bank", "DFCC Bank", "Pan Asia Bank", "Seylan Bank", "Other" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });

        txtAmount.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtAmount.setCaretColor(new java.awt.Color(116, 7, 7));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        lblOrderID9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID9.setText("Bank");

        btnChqPay.setBackground(new java.awt.Color(255, 255, 255));
        btnChqPay.setText("Save");
        btnChqPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChqPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChqPayActionPerformed(evt);
            }
        });

        lblOrderID10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID10.setText("Total");

        txtTot2.setEditable(false);
        txtTot2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTot2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtTot2.setCaretColor(new java.awt.Color(116, 7, 7));
        txtTot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTot2ActionPerformed(evt);
            }
        });

        lblOrderID11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOrderID11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderID11.setText("Amount");

        lblIfPay.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIfPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblIfPay, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(picDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnChqPay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblOrderID7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblOrderID10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtChqNo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTot2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblOrderID8, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(lblOrderID11, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(lblOrderID9, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(15, 15, 15)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblIfPay, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(picDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOrderID10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(txtTot2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2, 2, 2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtChqNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrderID7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                    .addGap(2, 2, 2)
                    .addComponent(lblOrderID8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGap(2, 2, 2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOrderID11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(2, 2, 2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOrderID9, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnChqPay)
                    .addGap(24, 24, 24)))
        );

        panelTab.addTab("<html>C<br>H<br>E<br>Q<br>U<br>E</html>", jPanel3);

        javax.swing.GroupLayout paneLayout = new javax.swing.GroupLayout(pane);
        pane.setLayout(paneLayout);
        paneLayout.setHorizontalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addComponent(panelTab, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paneLayout.setVerticalGroup(
            paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLayout.createSequentialGroup()
                .addComponent(panelTab, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        jButton1.doClick();
    }//GEN-LAST:event_txtCashActionPerformed

    private void txtCashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyReleased
        Validation.priceText(txtCash);
        if (!txtCash.getText().isEmpty()) {
            calcBalance();
        } else {
            txtBalance.setText("");
        }
    }//GEN-LAST:event_txtCashKeyReleased

    private void txtCashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyTyped
        Validation.priceText(txtCash);
        if (!txtCash.getText().isEmpty()) {
            calcBalance();
        } else {
            txtBalance.setText("");
        }
    }//GEN-LAST:event_txtCashKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txtCash.getText().isEmpty()) {
            try {
                MyPayment payment;
                if (Double.parseDouble(txtCash.getText()) - Double.parseDouble(txtTot.getText()) >= 0) {
                    payment = new MyPayment(getPID(), getDate(), Double.parseDouble(txtTot.getText()), cid);
                } else {
                    payment = new MyPayment(getPID(), getDate(), Double.parseDouble(txtCash.getText()), cid);
                }

                int addPayment = MyPaymentController.addMyPayment(payment);
                if (addPayment > 0) {
                    System.out.println(AccountsController.addAccount(new Accounts(0, HomeFrame.user.getUid(), "", "", 2, "Withdraw(GRN)", -payment.getAmount())));
                    JOptionPane.showMessageDialog(this, "payment Added");
                    if (!chkChq.isSelected()) {
                        dispose();
                    } else {
                        cash = Double.valueOf(txtCash.getText());
                        lblIfPay.setText("Cash Pay - " + cash);
                        lblOrderID10.setText("Balance");
                        txtTot2.setText(txtBalance.getText());
                        panelTab.setSelectedIndex(1);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "payment fail");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                ex.printStackTrace();
                StringWriter sw = new StringWriter();
                JOptionPane.showMessageDialog(this, ex.getMessage());
                ex.printStackTrace(new PrintWriter(sw));
                String trace = sw.toString();
                LoggerFileAcceess.exceptionLogger(trace);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Cash is empty!");
            txtCash.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotActionPerformed

    private void chkChqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkChqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkChqActionPerformed

    private void txtChqNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChqNo1ActionPerformed
        if (!txtChqNo1.getText().isEmpty()) {
            picDate.requestFocus();
        }
    }//GEN-LAST:event_txtChqNo1ActionPerformed

    private void btnChqPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChqPayActionPerformed
        if (txtChqNo1.getText().isEmpty()) {
            getToolkit().beep();
            txtChqNo1.requestFocus();
        } else if (!validateChqDay()) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "System can only accept chaques dated to today or future !");
        } else if (txtAmount.getText().isEmpty()) {
            getToolkit().beep();
            txtAmount.requestFocus();
        } else {
            try {
                MyPayment payment = new MyPayment(getPID(), getDate(), Double.parseDouble(txtAmount.getText()), cid);

                int addPayment = MyPaymentController.addMyPayment(payment);
                if (addPayment > 0) {
                    System.out.println(AccountsController.addAccountChq(new Accounts(0, HomeFrame.user.getUid(), getChqDate(), "", 2, "Withdraw(GRN)", -payment.getAmount())));
                    biz.project.cms.model.MyCheque cc = new MyCheque(txtChqNo1.getText(), getChqDate(), combo.getSelectedItem().toString(), payment.getPaymentId());
                    int added = MyChequeController.addMyCheque(cc);
                    if (added > 0) {
                        JOptionPane.showMessageDialog(this, "Cheque successfully added !");
                        dispose();
                    } else {
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(this, "Cheque add fail!");
                    }
                } else {
                    getToolkit().beep();
                    JOptionPane.showMessageDialog(this, "Payment add fail!");
                }
            } catch (ClassNotFoundException | SQLException ex) {
                StringWriter sw = new StringWriter();
                JOptionPane.showMessageDialog(this, ex.getMessage());
                ex.printStackTrace(new PrintWriter(sw));
                String trace = sw.toString();
                LoggerFileAcceess.exceptionLogger(trace);
            }
        }
    }//GEN-LAST:event_btnChqPayActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        if (!txtAmount.getText().isEmpty()) {
            combo.showPopup();
            combo.requestFocus();
        }
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtTot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTot2ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed

    }//GEN-LAST:event_comboActionPerformed

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnChqPay.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboKeyPressed

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        Validation.priceText(txtAmount);        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountKeyReleased

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        Validation.priceText(txtAmount);          // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountKeyTyped

    private void txtChqNo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChqNo1KeyReleased
        Validation.limitesIntegers(txtChqNo1, 18);          // TODO add your handling code here:
    }//GEN-LAST:event_txtChqNo1KeyReleased

    private void txtChqNo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChqNo1KeyTyped
        Validation.limitesIntegers(txtChqNo1, 18);              // TODO add your handling code here:
    }//GEN-LAST:event_txtChqNo1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGRNPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGRNPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGRNPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGRNPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddGRNPay dialog = new AddGRNPay(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChqPay;
    private javax.swing.JCheckBox chkChq;
    private javax.swing.JComboBox combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblIfPay;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblOrderID1;
    private javax.swing.JLabel lblOrderID10;
    private javax.swing.JLabel lblOrderID11;
    private javax.swing.JLabel lblOrderID2;
    private javax.swing.JLabel lblOrderID3;
    private javax.swing.JLabel lblOrderID7;
    private javax.swing.JLabel lblOrderID8;
    private javax.swing.JLabel lblOrderID9;
    private javax.swing.JPanel pane;
    private javax.swing.JTabbedPane panelTab;
    private org.jdesktop.swingx.JXDatePicker picDate;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChqNo1;
    private javax.swing.JTextField txtTot;
    private javax.swing.JTextField txtTot2;
    // End of variables declaration//GEN-END:variables
    private void calcBalance() {
        double balance = Double.parseDouble(txtCash.getText()) - Double.parseDouble(txtTot.getText());
        txtBalance.setText(balance + "");
    }

    public void setCID(String id) {
        this.cid = id;
        lblOrderID.setText("Order ID - " + id);
    }

    public void setAmount(double amount) {
        txtTot.setText(amount + "");
        txtTot2.setText(amount + "");
    }

    private String getDate() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat.format(date);
    }

    private boolean validateChqDay() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");

        Date date1 = picDate.getDate();
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyyMMdd");

        return Integer.parseInt(dateFormat.format(date)) <= Integer.parseInt(dateFormat1.format(date1));
    }

    private String getChqDate() {
        Date date1 = picDate.getDate();
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
        return dateFormat1.format(date1);
    }

    private String getPID() throws SQLException, ClassNotFoundException {
        return IdGenerator.getNewId(5);
    }
}
